### ISSUE TITLE
Raphael sets SVG element width and height to 512/384 by default

### ISSUE THREAD

**Issue by keithamus** [DmitryBaranovskiy/raphael#558]
When creating a new Raphael object, on line [4726](https://github.com/DmitryBaranovskiy/raphael/blob/master/raphael.js#L4726) and [4727](https://github.com/DmitryBaranovskiy/raphael/blob/master/raphael.js#L4727), Raphael decides to set a default width of 512px and a default height of 384px.

Unfortunately this means that creating a Raphael object that will be injected into a container is given this fixed width, which means the width has to then be explicitly set in CSS over the top, which is bad. It also stops implicit widths in CSS working, like this:

``` css
/* This should make the element stretch to the parent containers dimensions */
svg {
   position: absolute;
   top: 0;
   bottom: 0;
   left: 0;
   right: 0;
}
```

I for one would prefer no defaults to be set, or failing that the option to turn off these defaults.
